name: Compile and Run C Program

on: [push, pull_request]  # Trigger action on code push or pull request creation

jobs:
  run:
    runs-on: ubuntu-latest  # Environment to use (Ubuntu)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetch the code from the repository

      - name: Install GCC Compiler
        run: |
          sudo apt-get update  # Update package list
          sudo apt-get install -y gcc  # Install GCC compiler

      - name: Compile All C Files
        run: |
          # Loop through each .c file in the repository
          for file in *.c; do
            echo "Compiling $file..."
            gcc "$file" -o "${file%.c}.out"  # Compile each file into a .out executable
          done

      - name: Run All Compiled Programs
        run: |
          # Loop through each .out file
          for file in *.out; do
            echo "Running $file..."
            chmod +x "$file"  # Ensure each compiled .out file is executable
            ./$file  # Run the compiled file
          done
